"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.binary_sensor import (
    BinarySensorEntity,
    BinarySensorEntityDescription,
)
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription
from .zones import ZoneInfo


@dataclass(frozen=True, kw_only=True)
class ProxonBinarySensorEntityDescription(BinarySensorEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed binary_sensor."""


class ProxonBinarySensor(ProxonEntity, BinarySensorEntity):
    """A single Proxon binary_sensor entity."""

    entity_description: ProxonBinarySensorEntityDescription

    @property
    def is_on(self) -> bool:
        return bool(self._value)


BINARY_SENSOR_DESCRIPTIONS: tuple[ProxonBinarySensorEntityDescription, ...] = (
    ProxonBinarySensorEntityDescription(
        key='proxon_heizelemente_global',
        component='lueftung',
        field='proxon_heizelemente_global',
        name='Proxon Heizelemente Global',
        has_entity_name=False,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_kompressor_status',
        component='heizstab_status',
        field='proxon_kompressor_status',
        name='Proxon Kompressor Status',
        has_entity_name=False,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_heizstab_status',
        component='heizstab_status',
        field='proxon_heizstab_status',
        name='Proxon Heizstab Status',
        has_entity_name=False,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_r3_solar',
        component='heizstab_status',
        field='r3_solar',
        translation_key='proxon_r3_solar',
        has_entity_name=True,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_r5_ventilator',
        component='heizstab_status',
        field='r5_ventilator',
        translation_key='proxon_r5_ventilator',
        has_entity_name=True,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_r6_abtau',
        component='heizstab_status',
        field='r6_abtau',
        translation_key='proxon_r6_abtau',
        has_entity_name=True,
    ),
)

def _zone_descriptions(zones: list[ZoneInfo]) -> list[ProxonBinarySensorEntityDescription]:
    """Tastensperre status for HNBP/NBPn zones - read-only, see zones.py."""
    out: list[ProxonBinarySensorEntityDescription] = []
    for zone in zones:
        if zone.kind == "nb":
            out.append(
                ProxonBinarySensorEntityDescription(
                    key=f"proxon_tastensperre_{zone.slug}",
                    component="nb_zones_holding",
                    field="tastensperre",
                    zone_index=zone.zone_index,
                    translation_key="proxon_zone_tastensperre",
                    has_entity_name=True,
                    entity_category=EntityCategory.DIAGNOSTIC,
                )
            )
    return out


from .filter import FILTER_REMINDER_DESCRIPTION, ProxonFilterReminderBinarySensor
from .heizelement_status import heizelement_status_entities


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon binary_sensor entities."""
    coordinator = entry.runtime_data.coordinator
    entities = [ProxonBinarySensor(coordinator, d) for d in BINARY_SENSOR_DESCRIPTIONS]
    entities += [ProxonBinarySensor(coordinator, d) for d in _zone_descriptions(entry.runtime_data.zones)]
    entities.extend([ProxonFilterReminderBinarySensor(coordinator, FILTER_REMINDER_DESCRIPTION), *heizelement_status_entities(coordinator, entry.runtime_data.zones)])
    async_add_entities(entities)

