"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.binary_sensor import (
    BinarySensorEntity,
    BinarySensorEntityDescription,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription


@dataclass(frozen=True, kw_only=True)
class ProxonBinarySensorEntityDescription(BinarySensorEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed binary_sensor."""


class ProxonBinarySensor(ProxonEntity, BinarySensorEntity):
    """A single Proxon binary_sensor entity."""

    entity_description: ProxonBinarySensorEntityDescription

    @property
    def is_on(self) -> bool:
        return bool(self._value)


BINARY_SENSOR_DESCRIPTIONS: tuple[ProxonBinarySensorEntityDescription, ...] = (
    ProxonBinarySensorEntityDescription(
        key='proxon_kompressor_status',
        component='heizstab_status',
        field='proxon_kompressor_status',
        name='Proxon Kompressor Status',
        has_entity_name=False,
    ),
    ProxonBinarySensorEntityDescription(
        key='proxon_heizstab_status',
        component='heizstab_status',
        field='proxon_heizstab_status',
        name='Proxon Heizstab Status',
        has_entity_name=False,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon binary_sensor entities."""
    coordinator = entry.runtime_data.coordinator
    async_add_entities(ProxonBinarySensor(coordinator, d) for d in BINARY_SENSOR_DESCRIPTIONS)

