"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand.

The central (non-zone) Components below are generated from proxon.yaml + the
Excel register list. The zone wiring (ZBP/HNBP/NBPn) is fixed boilerplate that
always looks like this, regardless of curation - see zones.py for the Component
definitions themselves.
"""

from __future__ import annotations

from modbus_connection.model import Device

from . import registers_holding as rh
from . import registers_input as ri
from .zones import (
    ZbpZone,
    ZbpZoneInput,
    build_nb_zones_group,
    build_nb_zones_input_group,
)


class ProxonDevice(Device):
    """Root device object: one attribute per Component, wired to the shared ModbusUnit."""

    def __init__(self, unit, *, zone_count: int = 0) -> None:
        """``zone_count`` is the number of NBP1..NBPn zones (from the config
        entry); the HNBP slot is always modeled as an extra, index-0 zone.
        """
        super().__init__(unit)
        self.zone_count = zone_count
        self.zbp = ZbpZone(unit)
        self.zbp_input = ZbpZoneInput(unit)
        self.nb_zones_holding = build_nb_zones_group(zone_count + 1)(unit)
        self.nb_zones_input = build_nb_zones_input_group(zone_count + 1)(unit)
        self.lueftung = rh.Lueftung(unit)
        self.t300_warmwasser = rh.T300Warmwasser(unit)
        self.geraetefilter = rh.Geraetefilter(unit)
        self.modbus_status_holding = rh.ModbusStatusHolding(unit)
        self.stundenzaehler = rh.Stundenzaehler(unit)
        self.bypass = rh.Bypass(unit)
        self.hauptmenu_info = rh.HauptmenuInfo(unit)
        self.zu_abluft = ri.ZuAbluft(unit)
        self.warmwasser_input = ri.WarmwasserInput(unit)
        self.heizstab_status = ri.HeizstabStatus(unit)
        self.sonstiges_input = ri.SonstigesInput(unit)
        self.betriebswerte = ri.Betriebswerte(unit)
        self.heizmodule = ri.Heizmodule(unit)

    def components(self):
        """All components, for async_update()/failure tracking."""
        return (
            self.zbp,
            self.zbp_input,
            self.nb_zones_holding,
            self.nb_zones_input,
            self.lueftung,
            self.t300_warmwasser,
            self.geraetefilter,
            self.modbus_status_holding,
            self.stundenzaehler,
            self.bypass,
            self.hauptmenu_info,
            self.zu_abluft,
            self.warmwasser_input,
            self.heizstab_status,
            self.sonstiges_input,
            self.betriebswerte,
            self.heizmodule,
        )

