"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from modbus_connection.model import Device

from . import registers_holding as rh
from . import registers_input as ri


class ProxonDevice(Device):
    """Root device object: one attribute per Component, wired to the shared ModbusUnit."""

    def __init__(self, unit) -> None:
        super().__init__(unit)
        self.heizelemente_switches = rh.HeizelementeSwitches(unit)
        self.tastensperre = rh.Tastensperre(unit)
        self.offset_temperaturen = rh.OffsetTemperaturen(unit)
        self.mitteltemperaturen = rh.Mitteltemperaturen(unit)
        self.lueftung = rh.Lueftung(unit)
        self.t300_warmwasser = rh.T300Warmwasser(unit)
        self.geraetefilter = rh.Geraetefilter(unit)
        self.modbus_status_holding = rh.ModbusStatusHolding(unit)
        self.stundenzaehler = rh.Stundenzaehler(unit)
        self.bypass = rh.Bypass(unit)
        self.hauptmenu_info = rh.HauptmenuInfo(unit)
        self.zonen_temperaturen = ri.ZonenTemperaturen(unit)
        self.zu_abluft = ri.ZuAbluft(unit)
        self.warmwasser_input = ri.WarmwasserInput(unit)
        self.heizstab_status = ri.HeizstabStatus(unit)
        self.sonstiges_input = ri.SonstigesInput(unit)
        self.betriebswerte = ri.Betriebswerte(unit)
        self.heizmodule = ri.Heizmodule(unit)
        self.bedienteil_status = ri.BedienteilStatus(unit)

    def components(self):
        """All components, for async_update()/failure tracking."""
        return (
            self.heizelemente_switches,
            self.tastensperre,
            self.offset_temperaturen,
            self.mitteltemperaturen,
            self.lueftung,
            self.t300_warmwasser,
            self.geraetefilter,
            self.modbus_status_holding,
            self.stundenzaehler,
            self.bypass,
            self.hauptmenu_info,
            self.zonen_temperaturen,
            self.zu_abluft,
            self.warmwasser_input,
            self.heizstab_status,
            self.sonstiges_input,
            self.betriebswerte,
            self.heizmodule,
            self.bedienteil_status,
        )

