"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.number import NumberEntity, NumberEntityDescription
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription


@dataclass(frozen=True, kw_only=True)
class ProxonNumberEntityDescription(NumberEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed number."""


class ProxonNumber(ProxonEntity, NumberEntity):
    """A single Proxon number entity."""

    entity_description: ProxonNumberEntityDescription

    @property
    def native_value(self):
        return self._value

    async def async_set_native_value(self, value: float) -> None:
        await self._async_write(value)


NUMBER_DESCRIPTIONS: tuple[ProxonNumberEntityDescription, ...] = (
    ProxonNumberEntityDescription(
        key='proxon_soll_temperatur_zone_2_og_bei_keine_hnbp',
        component='offset_temperaturen',
        field='soll_temperatur_zone_2_og_bei_keine_hnbp',
        translation_key='proxon_soll_temperatur_zone_2_og_bei_keine_hnbp',
        native_unit_of_measurement='°C',
        native_min_value=10.0,
        native_max_value=30.0,
        native_step=0.01,
    ),
    ProxonNumberEntityDescription(
        key='proxon_minimum_frischlufttemperatur_bypass_aus',
        component='bypass',
        field='minimum_frischlufttemperatur_bypass_aus',
        translation_key='proxon_minimum_frischlufttemperatur_bypass_aus',
        entity_category=EntityCategory.CONFIG,
        native_unit_of_measurement='°C',
        native_min_value=8.0,
        native_max_value=20.0,
        native_step=0.01,
    ),
    ProxonNumberEntityDescription(
        key='proxon_bypasstemperatur_hysterese',
        component='bypass',
        field='bypasstemperatur_hysterese',
        translation_key='proxon_bypasstemperatur_hysterese',
        entity_category=EntityCategory.CONFIG,
        native_unit_of_measurement='°C',
        native_min_value=0.0,
        native_max_value=10.0,
        native_step=0.01,
    ),
    ProxonNumberEntityDescription(
        key='proxon_bypass_laufzeit_an_aus',
        component='bypass',
        field='bypass_laufzeit_an_aus',
        translation_key='proxon_bypass_laufzeit_an_aus',
        entity_category=EntityCategory.CONFIG,
        native_unit_of_measurement='Sekunden',
        native_min_value=10.0,
        native_max_value=20.0,
        native_step=1.0,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon number entities."""
    coordinator = entry.runtime_data.coordinator
    async_add_entities(ProxonNumber(coordinator, d) for d in NUMBER_DESCRIPTIONS)

