"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand.

Re-run ``python tools/generate_registers.py`` from the repository root after
changing the curation rules in that script (e.g. to include more registers
from the Excel register list).
"""

from __future__ import annotations

from modbus_connection.model import Component, gauge, integer


class ZuAbluft(Component):
    """Zu-/Ab-/Fort-/Frischluft-Temperaturen, CO2, Luftfeuchte. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_co2_wohnzimmer = integer(21, signed=True, unit='ppm')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_luftfeuchte_wohnzimmer = integer(22, signed=True, unit='%')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_temperatur_zuluft = gauge(195, 0.01, signed=False, unit='°C')  # Proxon Temperatur Zuluft
    proxon_temperatur_abluft = gauge(196, 0.01, signed=False, unit='°C')  # Proxon Temperatur Abluft
    proxon_temperatur_fortluft = gauge(197, 0.01, signed=False, unit='°C')  # Proxon Temperatur Fortluft
    proxon_temperatur_frischluft = gauge(198, 0.01, signed=False, unit='°C')  # Proxon Temperatur Frischluft

class WarmwasserInput(Component):
    """T300 Warmwasser Ist-Temperaturen. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_temperatur_wasser_unten = gauge(813, 0.1, signed=False, unit='°C', offset=-100)  # Proxon Temperatur Wasser Unten
    proxon_ist_temperatur_wasser = gauge(814, 0.1, signed=False, unit='°C', offset=-100)  # Proxon Ist-Temperatur Wasser

class HeizstabStatus(Component):
    """T300 Heizstab-/Kompressorstatus (binäre Sensoren). Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_kompressor_status = integer(824, signed=False, unit='AUS/AN')  # Proxon Kompressor Status
    proxon_heizstab_status = integer(826, signed=False, unit='AUS/AN')  # Proxon Heizstab Status
    r3_solar = integer(825, signed=False, unit='AUS/AN')  # R3:Solar
    r5_ventilator = integer(827, signed=False, unit='AUS/AN')  # R5:Ventilator
    r6_abtau = integer(828, signed=False, unit='AUS/AN')  # R6:Abtau

class SonstigesInput(Component):
    """Betriebsart, Lüfterstufe, Stromaufnahme u.a. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_stromaufnahme_total = gauge(25, 0.1, signed=True, unit='W')  # Stromaufnahme
    proxon_lueftungsstufe_ventilator_zuluft = integer(154, signed=True)  # Proxon Lüftungsstufe Ventilator Zuluft
    proxon_aktueller_betrieb = integer(241, signed=True)  # Proxon aktueller Betrieb
    proxon_heizelement_status = integer(574, signed=True, unit='Binär')  # Bit9:R10 Bit8:R9 Bit7:R8 Bit6:R7 Bit5:R6 Bit4:R5 Bit3:R4 Bit2:R3 Bit1:R2 Bit0:R1
    proxon_heizelement_status_2 = integer(583, signed=True, unit='Binär')  # Bit9:R10 Bit8:R9 Bit7:R8 Bit6:R7 Bit5:R6 Bit4:R5 Bit3:R4 Bit2:R3 Bit1:R2 Bit0:R1

class Betriebswerte(Component):
    """Ventilatoren, Leistung, JAZ-Zähler, Betriebsart/Status/Fehlercodes, Messtemperaturen T1-T14, Ventilpositionen, Drücke. Neu hinzugefügt."""

    register_space = "input"

    akt_drehzahl_zuluftventilator = integer(0, signed=True, unit='rpm')  # Akt.Drehzahl ZuLuftventilator
    akt_drehzahl_abluftventilator = integer(1, signed=True, unit='rpm')  # Akt.Drehzahl AbLuftventilator
    ptc_kuehlen_freigabe = integer(3, signed=True)  # PTC Kühlen Freigabe
    nacht_temp_bei_zeitprogramm = gauge(4, 0.01, signed=False, unit='°C')  # Nacht Temp Bei Zeitprogramm
    firmwareversionhaupptplatine = gauge(5, 0.1, signed=True)  # FirmwareVersionHaupptPlatine
    relaisstatushauptplatine = integer(8, signed=True, unit='Binär')  # RelaisStatusHauptPlatine
    es997stufe = integer(10, signed=True)  # ES997Stufe
    sollzone2 = gauge(11, 0.01, signed=False)  # SollZone2
    adsusaettemp = integer(12, signed=True)  # ADSusaetTemp
    adausentemp = integer(13, signed=True)  # ADAusenTemp
    clockhour = integer(14, signed=True)  # ClockHour
    clockmin = integer(15, signed=True)  # ClockMin
    clockday = integer(16, signed=True)  # ClockDay
    clockdate = integer(17, signed=True)  # ClockDate
    clockmonth = integer(18, signed=True)  # ClockMonth
    powerpcb = gauge(19, 0.1, signed=True)  # PowerPCB
    powerfu = gauge(20, 0.1, signed=True)  # PowerFU
    akt_betriebsart = integer(23, signed=True)  # Akt. Betriebsart
    p18_druckventilator = gauge(24, 0.1, signed=True, unit='Pa')  # P18 Druckventilator
    air_m3_h = gauge(26, 0.1, signed=True)  # Air m3/h
    jaz_komp_1min = gauge(27, 0.01, signed=True)  # JAZ KOMP 1min
    jaz_komp_1_stunde = gauge(28, 0.01, signed=True)  # JAZ KOMP  1 stunde
    jaz_komp_24_stunde = gauge(29, 0.01, signed=True)  # JAZ KOMP  24 stunde
    jaz_komp_365_tage = gauge(30, 0.01, signed=True)  # JAZ KOMP  365 tage
    jaz_komp_days = integer(31, signed=True)  # JAZ KOMP  days
    jaz_total_1min = gauge(32, 0.01, signed=True)  # JAZ Total 1min
    jaz_total_1_stunde = gauge(33, 0.01, signed=True)  # JAZ Total  1 stunde
    jaz_total_24_stunde = gauge(34, 0.01, signed=True)  # JAZ Total  24 stunde
    jaz_total_365_tage = gauge(35, 0.01, signed=True)  # JAZ Total  365 tage
    jaz_total_days = integer(36, signed=True)  # JAZ Total  days
    hp_nmt_state = integer(37, signed=True)  # HP_NMT_State
    stufebeizeitprg = integer(38, signed=True)  # StufeBeiZeitPrg
    umluftaktive = integer(39, signed=True)  # UmluftAktive
    temphbdeintern = gauge(42, 0.01, signed=False)  # TempHBDEintern
    stoerung = integer(47, signed=True)  # Stoerung
    errorstatus1 = integer(48, signed=True)  # ErrorStatus1
    errorstatus2 = integer(49, signed=True)  # ErrorStatus2
    errorstatus3 = integer(50, signed=True)  # ErrorStatus3
    errorstatus4 = integer(51, signed=True)  # ErrorStatus4
    firmwareversionnebenplatine = gauge(150, 0.1, signed=True)  # FirmwareVersionNebenPlatine
    wprelaisstatus = integer(151, signed=True, unit='Binär')  # WpRelaisStatus
    statusventilatoren = integer(152, signed=True)  # StatusVentilatoren
    ventilatorfehlerrestzeit = integer(153, signed=True, unit='Sekunden')  # VentilatorFehlerRestZeit
    akt_ventilator_spannung_zuluft = gauge(155, 0.01, signed=True, unit='Volt')  # Akt.Ventilator Spannung ZuLuft
    akt_ventilator_spannung_abluft = gauge(156, 0.01, signed=True, unit='Volt')  # Akt.Ventilator Spannung AbLuft
    errorflagsnebenplatine = integer(157, signed=True, unit='Binär')  # ErrorFlagsNebenPlatine
    bypassresthaltezeit = integer(158, signed=True, unit='Sekunden')  # BypassRestHaltezeit
    schieber_position = integer(159, signed=True)  # Schieber Position
    schieberresthaltezeit = gauge(160, 0.1, signed=True, unit='Sekunden')  # SchieberRestHaltezeit
    schieberverfahrauftrag = gauge(161, 0.1, signed=True, unit='Sekunden')  # SchieberVerfahrauftrag
    status_kompressor = integer(162, signed=True)  # Status Kompressor
    wptimerschonzeit = integer(163, signed=True, unit='Sekunden')  # WpTimerSchonzeit
    wptimermindestlaufzeit = integer(164, signed=True, unit='Sekunden')  # WpTimerMindestlaufzeit
    wpabtautimer = integer(165, signed=True, unit='Minuten')  # WpAbtauTimer
    wptimerabtaunachlauf = integer(166, signed=True, unit='Sekunden')  # WpTimerAbtauNachlauf
    p19_druckdiff_abtau = gauge(167, 0.01, signed=True, unit='Pa')  # P19 Druckdiff. Abtau
    wptimerentlastung = integer(168, signed=True, unit='Sekunden')  # WpTimerEntlastung
    wpminabtauintervalltimer = gauge(169, 0.01, signed=True, unit='Minuten')  # WpMinAbtauIntervallTimer
    fu_errorcode = integer(170, signed=True)  # FU_ErrorCode
    akt_leistung_kompressor = gauge(171, 0.01, signed=True, unit='%')  # Akt.Leistung: Kompressor
    fu_errorcode2 = integer(172, signed=True)  # FU_ErrorCode2
    delta_sauggas_kondensator_temp = gauge(173, 0.01, signed=False, unit='°C')  # Delta Sauggas Kondensator Temp
    fu_fatalfoferror = integer(174, signed=True)  # FU_FatalFOFerror
    t5_vorverdampfer = gauge(175, 0.01, signed=False, unit='°C')  # T5 VorVerdampfer
    t6_verdampfer = gauge(176, 0.01, signed=False, unit='°C')  # T6 Verdampfer
    t8_nach_vorwaerme = gauge(177, 0.01, signed=False, unit='°C')  # T8 Nach Vorwärme
    t12_vor_kondensator = gauge(178, 0.01, signed=False, unit='°C')  # T12 Vor Kondensator
    t10_kondensator = gauge(179, 0.01, signed=False, unit='°C')  # T10 Kondensator
    t13_kompressor = gauge(180, 0.01, signed=False, unit='°C')  # T13 Kompressor
    t9_t_aul_vor_ewt = gauge(181, 0.01, signed=False, unit='°C')  # T9 T_AUL_vor_EWT
    wpabtauschwellecounter = integer(182, signed=True, unit='Sekunden')  # WpAbtauSchwelleCounter
    lscontrolfu_status = integer(183, signed=True)  # LsControlFU_Status
    lscontrolfuerrorinput = integer(184, signed=True, unit='AUS/AN')  # LsControlFUErrorInput
    furesettimecounter = integer(185, signed=True, unit='Sekunden')  # FuResetTimeCounter
    fufehlerverz = integer(186, signed=True, unit='Sekunden')  # FuFehlerVerz
    fuerrorcounter = integer(187, signed=True)  # FuErrorCounter
    lscontrolhightime = gauge(188, 0.01, signed=True, unit='Sekunden')  # LsControlHighTime
    lscontrolpulsbreite = gauge(189, 0.01, signed=True, unit='Sekunden')  # LsControlPulsbreite
    akt_drehzahl_kompressor = integer(190, signed=True, unit='ppm')  # Akt.Drehzahl: Kompressor
    tempzusatz1 = gauge(191, 0.01, signed=False, unit='°C')  # TempZusatz1
    zuluftsollzone1 = gauge(192, 0.01, signed=False, unit='°C')  # ZuluftSollZone1
    tempzusatz2 = gauge(193, 0.01, signed=False, unit='°C')  # TempZusatz2
    zuluftsollzone2 = gauge(194, 0.01, signed=False, unit='°C')  # ZuluftSollZone2
    tcanforderungluft = gauge(199, 0.01, signed=True, unit='%')  # TcAnforderungLuft
    conwpstoptimer = integer(200, signed=True, unit='Sekunden')  # ConWpStopTimer
    akt_max_leistung_kompressor = gauge(201, 0.01, signed=True, unit='%')  # Akt. Max.Leistung Kompressor
    delta_sauggas_verdampfer_temp = gauge(202, 0.01, signed=False, unit='°C')  # Delta Sauggas Verdampfer Temp
    e_ventil_kuehlung_position = integer(203, signed=True)  # E-Ventil Kühlung Position
    e_ventil_heizung_position = integer(204, signed=True)  # E-Ventil Heizung Position
    e_ventil_vorwaerme_position = integer(205, signed=True)  # E-Ventil Vorwärme Position
    p14_nd_verdampfer = gauge(206, 0.001, signed=True, unit='bar')  # P14 ND. Verdampfer
    t14_sauggas_nach_kondensator = gauge(207, 0.01, signed=False, unit='°C')  # T14 Sauggas nach Kondensator
    t11_sauggas_nach_verdampfer = gauge(208, 0.01, signed=False, unit='°C')  # T11 Sauggas nach Verdampfer
    abtaudruck = gauge(209, 0.01, signed=True, unit='Pa')  # AbtauDruck
    einausstatus = integer(210, signed=True, unit='Binär')  # EinAusStatus
    akt_ventilator_stufe_abluft = integer(211, signed=True)  # Akt.Ventilator Stufe Abluft
    schieberberechnungrestzeit = integer(212, signed=True, unit='Sekunden')  # SchieberBerechnungRestZeit
    wptimerauslauf = integer(214, signed=True, unit='Sekunden')  # WpTimerAuslauf
    restwpzusatzabtauverzzeit = integer(215, signed=True, unit='Sekunden')  # RestWpZusatzAbtauVerzZeit
    verdampfertemperatur_druck = gauge(216, 0.01, signed=False, unit='°C')  # Verdampfertemperatur (Druck)
    fuinittimecounter = gauge(217, 0.01, signed=True, unit='Sekunden')  # FuInitTimeCounter
    wpmaxr407_druckzutemp = gauge(218, 0.01, signed=False, unit='°C')  # WpMaxR407_DruckZuTemp
    stufectrlby = integer(219, signed=True)  # StufeCtrlBy
    erdwaerme_zustand = integer(220, signed=True, unit='AUS/AN')  # Erdwärme Zustand
    zustand_magnetventil_aus_an = integer(221, signed=True, unit='AUS/AN')  # Zustand Magnetventil AUS/AN
    zustand_bypass = integer(222, signed=True, unit='AUS/AN')  # Zustand Bypass
    zustand_4_wegeventil_heizen_kuehlen = integer(223, signed=True, unit='AUS/AN')  # Zustand 4-Wegeventil Heizen/Kühlen
    vorwaermeventilzustand = integer(224, signed=True, unit='AUS/AN')  # VorwärmeVentilZustand
    fuleistungmodbus = integer(225, signed=True, unit='%')  # FuLeistungModbus
    fu_temperaturepowermodule = integer(233, signed=False, unit='°C')  # FU_TemperaturePowermodule
    fu_temperaturecabinet = integer(234, signed=False, unit='°C')  # FU_TemperatureCabinet
    regluftstufezuluft = integer(238, signed=True)  # RegLuftStufeZuluft
    regluftstufeabluft = integer(239, signed=True)  # RegLuftStufeAbluft
    stepstatepreh = integer(240, signed=True)  # StepStatePreH
    stepsetpointpospreh = integer(242, signed=True)  # StepSetpointPosPreH
    stepstatecool = integer(243, signed=True)  # StepStateCool
    soll_ueberhitzung = gauge(244, 0.01, signed=False, unit='°C')  # Soll Überhitzung
    stepsetpointposcool = integer(245, signed=True)  # StepSetpointPosCool
    stepsetpointposheat = integer(247, signed=True)  # StepSetpointPosHeat
    stepstateheat = integer(248, signed=True)  # StepStateHeat
    delta_soll_t8_akt_t8 = gauge(249, 0.01, signed=False, unit='°C')  # Delta Soll T8 - Akt.T8
    fu_motorcurrent = gauge(250, 0.01, signed=False, unit='Ampere')  # FU_MotorCurrent
    sollzonentemperatur2 = gauge(251, 0.01, signed=False, unit='°C')  # SollZonenTemperatur2
    akt_min_ueberhitzung = gauge(252, 0.01, signed=False, unit='°C')  # Akt. Min. Überhitzung
    akt_max_ueberhitzung = gauge(253, 0.01, signed=False, unit='°C')  # Akt. Max. Überhitzung
    fu_motor_strom = gauge(254, 0.01, signed=True, unit='Ampere')  # FU Motor Strom
    regel_freigabe_restzeit_nach_abtau = integer(255, signed=True, unit='Sekunden')  # Regel Freigabe Restzeit Nach Abtau
    nachabtauleistungrestorevalue = gauge(256, 0.01, signed=True, unit='%')  # NachAbtauLeistungRestoreValue
    nachabtausuperheatrestorevalue = gauge(257, 0.01, signed=False, unit='°C')  # NachAbtauSuperheatRestoreValue
    fumaxrpmupdatatet_fl = integer(258, signed=True, unit='AUS/AN')  # FuMaxRpmUpdatatet_fl
    fumaxrpmset = integer(259, signed=True, unit='ppm')  # FuMaxRpmSet
    nachabtaumaxsuperheat = gauge(260, 0.01, signed=False, unit='°C')  # NachAbtauMaxSuperHeat
    eventilstartpostimeleft = integer(261, signed=True)  # EventilStartPosTimeLeft
    currentes997betriebsart = integer(262, signed=True)  # CurrentES997Betriebsart
    t2_1_zonentemperatur1 = gauge(263, 0.01, signed=False, unit='°C')  # T2.1 ZonenTemperatur1
    t2_2_zonentemperatur2 = gauge(264, 0.01, signed=False, unit='°C')  # T2.2 ZonenTemperatur2
    sollzonentemperatur1 = gauge(265, 0.01, signed=False, unit='°C')  # SollZonenTemperatur1

class Heizmodule(Component):
    """Status/Temperatur/Selbsttest der beiden PTC-Heizmodule. Neu hinzugefügt."""

    register_space = "input"

    heizmodul_1_selbsttest_ergebnis = integer(570, signed=True, unit='Binär')  # Heizmodul 1 Selbsttest-Ergebnis
    heizmodul_1_status = integer(571, signed=True)  # Heizmodul 1 Status
    heizmodul_1_temperatur = integer(573, signed=True, unit='°C')  # Heizmodul 1 Temperatur
    heizmodul_2_selbsttest_ergebnis = integer(579, signed=True, unit='Binär')  # Heizmodul 2 Selbsttest-Ergebnis
    heizmodul_2_status = integer(580, signed=True)  # Heizmodul 2 Status
    heizmodul_2_temperatur = integer(582, signed=True, unit='°C')  # Heizmodul 2 Temperatur

class T300Diagnose(Component):
    """T300 Kältekreis-Messwerte (T5/T6/T9/T11/T13, Drücke, Zustände, Fehlerzähler). Neu hinzugefügt."""

    register_space = "input"

    t5_vor_verdampfer = gauge(811, 0.1, signed=False, unit='°C')  # T5 Vor Verdampfer
    t6_verdampfer_2 = gauge(812, 0.1, signed=False, unit='°C')  # T6 Verdampfer
    t13_kompressor_2 = gauge(815, 0.1, signed=False, unit='°C')  # T13 Kompressor
    t11_sauggas_nach_verdampfer_2 = gauge(816, 0.1, signed=False, unit='°C')  # T11 Sauggas nach Verdampfer
    t9_extern_fuehler = gauge(817, 0.1, signed=False, unit='°C')  # T9 Extern Fühler
    p14_nd_verdampfer_2 = gauge(818, 0.01, signed=False, unit='bar')  # P14 ND. Verdampfer
    p19_druckdiff_abtau_2 = gauge(819, 0.01, signed=False, unit='Pa')  # P19 Druckdiff. Abtau
    e_ventil_posision = integer(820, signed=False)  # E-ventil Posision
    stepsetpointposision = integer(821, signed=False)  # StepSetpointPosision
    stepmicrosteppos = integer(822, signed=False)  # StepMicroStepPos
    stepstate = integer(823, signed=False)  # StepState
    verdampfertemperatur_druck_2 = gauge(829, 0.1, signed=False, unit='°C')  # Verdampfertemperatur (Druck)
    delta_sauggas_verdampfer_temp_2 = gauge(830, 0.1, signed=False, unit='°C')  # Delta Sauggas Verdampfer Temp
    nou_used = integer(831, signed=False)  # Nou_used
    hotairrestrictedcnt = integer(832, signed=False, unit='Sekunden')  # HotAirRestrictedCnt
    compressorstate = integer(833, signed=False)  # CompressorState
    notbetrieb = integer(834, signed=False)  # NotBetrieb
    wp_abtaurestrictedcnt = integer(835, signed=False, unit='Sekunden')  # WP_AbtauRestrictedCnt
    wp_statetimer = integer(836, signed=False, unit='Sekunden')  # WP_StateTimer
    abtaustate = integer(837, signed=False)  # AbtauState
    ventilator_geschwindigkeit = integer(838, signed=False, unit='%')  # Ventilator Geschwindigkeit
    abtaumaxtimeleft = integer(839, signed=False, unit='Sekunden')  # AbtauMaxTimeLeft
    abtauwaittime = integer(840, signed=False, unit='Sekunden')  # AbtauWaitTime
    kaltebetriebcnt = integer(841, signed=False, unit='Sekunden')  # KalteBetriebCnt
    rressorstatfehlercnt = integer(842, signed=False, unit='Sekunden')  # RressorstatFehlerCnt
    ventilatorfehlercnt = integer(844, signed=False, unit='Sekunden')  # VentilatorFehlerCnt
    komptempfehlerno4 = integer(845, signed=False, unit='Sekunden')  # KompTempFehlerNo4
    p14drukfehlercnt = integer(846, signed=False, unit='Sekunden')  # P14DrukFehlerCnt
    hourcntr2lowword = integer(847, signed=False, unit='Sekunden')  # HourCntR2LowWord
    hourcntr2hiword = integer(848, signed=False)  # HourCntR2HiWord
    hourcntr3lowword = integer(849, signed=False, unit='Sekunden')  # HourCntR3LowWord
    hourcntr3hiword = integer(850, signed=False)  # HourCntR3HiWord
    hourcntr4lowword = integer(851, signed=False, unit='Sekunden')  # HourCntR4LowWord
    hourcntr4hiword = integer(852, signed=False)  # HourCntR4HiWord
    hourcntr5lowword = integer(853, signed=False, unit='Sekunden')  # HourCntR5LowWord
    hourcntr5hiword = integer(854, signed=False)  # HourCntR5HiWord
    hourcntr6lowword = integer(855, signed=False, unit='Sekunden')  # HourCntR6LowWord
    hourcntr6hiword = integer(856, signed=False)  # HourCntR6HiWord
    filtercntlowword = integer(857, signed=False, unit='Sekunden')  # FilterCntLowWord
    filtercnthiword = integer(858, signed=False)  # FilterCntHiWord
    legionallacntlowword = integer(859, signed=False, unit='Sekunden')  # LegionallaCntLowWord
    legionallacnthiword = integer(860, signed=False)  # LegionallaCntHiWord
    fehlerlist = integer(861, signed=False, unit='Binär')  # FehlerList
    fanrpm = integer(862, signed=False, unit='rpm')  # FanRPM
    eco_nodeonoff = integer(863, signed=False, unit='AUS/AN')  # ECO_NodeOnOff
    pid_max_vordamfer_reduktion = integer(864, signed=False)  # pid_max_vordamfer_reduktion
    maxtempwp_reduktion = integer(865, signed=False)  # MaxTempWP_reduktion
    noteheizfreigabestate = integer(868, signed=False, unit='AUS/AN')  # NotEheizFreigabeState
    p19fehlercnt = integer(869, signed=False, unit='Sekunden')  # P19FehlerCnt
    p14fehlercnt = integer(870, signed=False, unit='Sekunden')  # P14FehlerCnt
    t5_fehlercnt = integer(871, signed=False, unit='Sekunden')  # T5_FehlerCnt
    t6_fehlercnt = integer(872, signed=False, unit='Sekunden')  # T6_FehlerCnt
    t20_fehlercnt = integer(873, signed=False, unit='Sekunden')  # T20_FehlerCnt
    t21_fehlercnt = integer(874, signed=False, unit='Sekunden')  # T21_FehlerCnt
    t13_fehlercnt = integer(875, signed=False, unit='Sekunden')  # T13_FehlerCnt
    t11_fehlercnt = integer(876, signed=False, unit='Sekunden')  # T11_FehlerCnt
    t9_fehlercnt = integer(877, signed=False, unit='Sekunden')  # T9_FehlerCnt
    kompmaxtempfehlercnt = integer(878, signed=False, unit='Sekunden')  # KompMaxTempFehlerCnt
    currentsetpoint = gauge(879, 0.1, signed=False, unit='°C')  # CurrentSetpoint
    number_of_restart = integer(880, signed=False)  # Number_of_restart
    firmware_ver = gauge(881, 0.1, signed=False)  # Firmware ver
    behaelderavg = gauge(882, 0.01, signed=False, unit='°C')  # BehaelderAvg
    superheattemp = gauge(883, 0.01, signed=False, unit='°C')  # SuperHeatTemp
    aktmaxsuperheat = gauge(884, 0.01, signed=False, unit='°C')  # AktMaxSuperHeat
    aktminsuperheat = gauge(885, 0.01, signed=False, unit='°C')  # AktMinSuperHeat
    superheatref = gauge(886, 0.01, signed=False, unit='°C')  # SuperHeatRef
    eventilstartpostimeleft_2 = integer(887, signed=False, unit='Sekunden')  # EventilStartPosTimeLeft
    regreleaseafterabtauresttime = integer(888, signed=False, unit='Sekunden')  # RegReleaseAfterAbtauRestTime
    afterabtausuperheatrestorevalue = integer(889, signed=False)  # AfterAbtauSuperheatRestoreValue
    afterabtaumaxsuperheat = gauge(890, 0.01, signed=False, unit='°C')  # AfterAbtauMaxSuperHeat
    abtaustarttemp = gauge(892, 0.1, signed=False, unit='°C')  # AbtauStartTemp
    hitze_begrenzung = integer(896, signed=False)  # Hitze Begrenzung
    kaelte_begrenzung = integer(897, signed=False)  # Kälte Begrenzung
    pv_t9_level = integer(898, signed=False, unit='%')  # PV T9 level
    pv_eheiz_an = integer(899, signed=False, unit='AUS/AN')  # PV Eheiz AN
    pv_wp_an = integer(900, signed=False, unit='AUS/AN')  # PV WP AN
