"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand.

Re-run ``python tools/generate_registers.py`` from the repository root after
changing the curation rules in that script (e.g. to include more registers
from the Excel register list).
"""

from __future__ import annotations

from modbus_connection.model import Component, gauge, integer


class HeizelementeSwitches(Component):
    """Heizelemente (PTC) global + je Raum ein-/ausschalten. Migriert 1:1 aus proxon.yaml."""

    proxon_heizelement_wohnzimmer = integer(187, signed=False, writable=True)  # Proxon Heizelement Wohnzimmer
    proxon_heizelement_partykeller = integer(253, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Partykeller
    proxon_heizelement_flur = integer(254, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Flur
    proxon_heizelement_schlafzimmer = integer(255, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Schlafzimmer
    proxon_heizelement_buero = integer(256, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Büro
    proxon_heizelement_lea = integer(257, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Lea
    proxon_heizelement_vorraum = integer(258, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Vorraum
    proxon_heizelement_werkstatt = integer(259, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelement Werkstatt
    proxon_heizelemente_global = integer(325, signed=False, unit='AUS/AN', writable=True)  # Proxon Heizelemente Global

class Tastensperre(Component):
    """Tastensperre der Bedienteile je Raum. Migriert 1:1 aus proxon.yaml."""

    proxon_tastensperre_partykeller = integer(273, signed=False, unit='AUS/AN', writable=True)  # Partykeller
    proxon_tastensperre_flur = integer(274, signed=False, unit='AUS/AN', writable=True)  # Flur
    proxon_tastensperre_schlafzimmer = integer(275, signed=False, unit='AUS/AN', writable=True)  # Schlafzimmer
    proxon_tastensperre_buero = integer(276, signed=False, unit='AUS/AN', writable=True)  # Büro
    proxon_tastensperre_lea = integer(277, signed=False, unit='AUS/AN', writable=True)  # Lea
    proxon_tastensperre_vorraum = integer(278, signed=False, unit='AUS/AN', writable=True)  # Vorraum
    proxon_tastensperre_werkstatt = integer(279, signed=False, unit='AUS/AN', writable=True)  # Werkstatt

class OffsetTemperaturen(Component):
    """Offset-/Soll-Temperaturen je Raum bzw. Zone. Migriert aus proxon.yaml, ergänzt um die Zonen-Sollwerte A09/A10."""

    proxon_offsettemperatur_wohnzimmer = gauge(70, 0.01, signed=True, unit='°C')  # Wohnzimmer
    proxon_offsettemperatur_partykeller = integer(213, signed=True, unit='°C')  # Partykeller
    proxon_offsettemperatur_flur = integer(214, signed=True, unit='°C')  # Flur
    proxon_offsettemperatur_schlafzimmer = integer(215, signed=True, unit='°C')  # Schlafzimmer
    proxon_offsettemperatur_buero = integer(216, signed=True, unit='°C')  # Büro
    proxon_offsettemperatur_lea = integer(217, signed=True, unit='°C')  # Lea
    proxon_offsettemperatur_vorraum = integer(218, signed=True, unit='°C')  # Vorraum
    proxon_offsettemperatur_werkstatt = integer(219, signed=True, unit='°C')  # Werkstatt
    soll_temperatur_zone_2_og_bei_keine_hnbp = gauge(75, 0.01, signed=True, unit='°C', writable=True)  # Soll Temperatur Zone 2 (OG) (Bei keine HNBP)

class Mitteltemperaturen(Component):
    """Gemittelte Raumtemperaturen je Raum. Migriert 1:1 aus proxon.yaml."""

    proxon_mitteltemperatur_partykeller = integer(233, signed=True, unit='°C')  # Partykeller
    proxon_mitteltemperatur_flur = integer(234, signed=True, unit='°C')  # Flur
    proxon_mitteltemperatur_schlafzimmer = integer(235, signed=True, unit='°C')  # Schlafzimmer
    proxon_mitteltemperatur_buero = integer(236, signed=True, unit='°C')  # Büro
    proxon_mitteltemperatur_lea = integer(237, signed=True, unit='°C')  # Lea
    proxon_mitteltemperatur_vorraum = integer(238, signed=True, unit='°C')  # Vorraum
    proxon_mitteltemperatur_werkstatt = integer(239, signed=True, unit='°C')  # Werkstatt

class Lueftung(Component):
    """Betriebsart, Lüfterstufe und Intensivlüftung. Migriert 1:1 aus proxon.yaml."""

    proxon_betriebsart = integer(16, signed=False)  # Proxon Betriebsart
    proxon_luefterstufe = integer(22, signed=False)  # Proxon Lüfterstufe
    proxon_intensivlueftung_restzeit = integer(133, signed=False, unit='Minuten')  # Proxon Intensivlüftung Restzeit
    proxon_intensivlueftung_sollzeit = integer(189, signed=False, unit='Minuten')  # Proxon Intensivlüftung Sollzeit

class T300Warmwasser(Component):
    """T300 Warmwasser-Heizstab. Migriert 1:1 aus proxon.yaml."""

    proxon_kuehlung = integer(62, signed=False, unit='AUS/AN', writable=True)  # Proxon Kuehlung
    proxon_soll_temperatur_wasser = gauge(2000, 0.1, signed=False, unit='°C')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    t300_heizstab = integer(2001, signed=False, writable=True)  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_heizstab_temperatur = gauge(2003, 0.1, signed=False, unit='°C')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).

class Geraetefilter(Component):
    """Standzeit/Nutzzeit des Gerätefilters. Migriert 1:1 aus proxon.yaml."""

    proxon_standzeit_fwt_geraetefilter = integer(460, signed=False, unit='Monate')  # Proxon Standzeit FWT Gerätefilter
    proxon_nutzzeit_fwt_geraetefilter = integer(469, signed=False)  # Proxon Nutzzeit FWT Gerätefilter

class ModbusStatusHolding(Component):
    """Modbus-Statusregister. Migriert 1:1 aus proxon.yaml."""

    proxon_modbus_status = integer(438, signed=False)  # Proxon Modbus Status

class Stundenzaehler(Component):
    """Betriebsstundenzähler (S01-S33). Neu hinzugefügt (nicht in der bisherigen proxon.yaml)."""

    stunden_fwt_an = integer(467, signed=False)  # Stunden FWT AN
    stunden_umluftfilter = integer(468, signed=False)  # Stunden Umluftfilter
    stunden_vorwaerme_an = integer(470, signed=False)  # Stunden Vorwärme AN
    stunden_umluft_an = integer(471, signed=False)  # Stunden Umluft AN
    stunden_fu_an = integer(472, signed=False)  # Stunden FU AN
    stunden_kompressor_kuehlen = integer(473, signed=False)  # Stunden Kompressor Kühlen
    stunden_kompressor_heizen = integer(474, signed=False)  # Stunden Kompressor Heizen
    stunden_abtau_an = integer(475, signed=False)  # Stunden Abtau AN
    stunden_ventilatoren_stufe_1 = integer(476, signed=False)  # Stunden Ventilatoren Stufe 1
    stunden_ventilatoren_stufe2 = integer(477, signed=False)  # Stunden Ventilatoren Stufe2
    stunden_ventilatoren_stufe_3 = integer(478, signed=False)  # Stunden Ventilatoren Stufe 3
    stunden_ventilatoren_stufe_4 = integer(479, signed=False)  # Stunden Ventilatoren Stufe 4
    stunden_ptc_heizmodul_1_relais_1_an = integer(487, signed=False)  # Stunden PTC Heizmodul 1 Relais 1 An
    stunden_ptc_heizmodul_1_relais_2_an = integer(488, signed=False)  # Stunden PTC Heizmodul 1 Relais 2 An
    stunden_ptc_heizmodul_1_relais_3_an = integer(489, signed=False)  # Stunden PTC Heizmodul 1 Relais 3 An
    stunden_ptc_heizmodul_1_relais_4_an = integer(490, signed=False)  # Stunden PTC Heizmodul 1 Relais 4 An
    stunden_ptc_heizmodul_1_relais_5_an = integer(491, signed=False)  # Stunden PTC Heizmodul 1 Relais 5 An
    stunden_ptc_heizmodul_1_relais_6_an = integer(492, signed=False)  # Stunden PTC Heizmodul 1 Relais 6 An
    stunden_ptc_heizmodul_1_relais_7_an = integer(493, signed=False)  # Stunden PTC Heizmodul 1 Relais 7 An
    stunden_ptc_heizmodul_1_relais_8_an = integer(494, signed=False)  # Stunden PTC Heizmodul 1 Relais 8 An
    stunden_ptc_heizmodul_1_relais_9_an = integer(495, signed=False)  # Stunden PTC Heizmodul 1 Relais 9 An
    stunden_ptc_heizmodul_1_relais_10_an = integer(496, signed=False)  # Stunden PTC Heizmodul 1 Relais 10 An
    stunden_ptc_heizmodul_2_relais_1_an = integer(497, signed=False)  # Stunden PTC Heizmodul 2 Relais 1 An
    stunden_ptc_heizmodul_2_relais_2_an = integer(498, signed=False)  # Stunden PTC Heizmodul 2 Relais 2 An
    stunden_ptc_heizmodul_2_relais_3_an = integer(499, signed=False)  # Stunden PTC Heizmodul 2 Relais 3 An
    stunden_ptc_heizmodul_2_relais_4_an = integer(500, signed=False)  # Stunden PTC Heizmodul 2 Relais 4 An
    stunden_ptc_heizmodul_2_relais_5_an = integer(501, signed=False)  # Stunden PTC Heizmodul 2 Relais 5 An
    stunden_ptc_heizmodul_2_relais_6_an = integer(502, signed=False)  # Stunden PTC Heizmodul 2 Relais 6 An
    stunden_ptc_heizmodul_2_relais_7_an = integer(503, signed=False)  # Stunden PTC Heizmodul 2 Relais 7 An
    stunden_ptc_heizmodul_2_relais_8_an = integer(504, signed=False)  # Stunden PTC Heizmodul 2 Relais 8 An
    stunden_ptc_heizmodul_2_relais_9_an = integer(505, signed=False)  # Stunden PTC Heizmodul 2 Relais 9 An
    stunden_ptc_heizmodul_2_relais_10_an = integer(506, signed=False)  # Stunden PTC Heizmodul 2 Relais 10 An

class Bypass(Component):
    """Bypass-Einstellungen (G01-G03). Neu hinzugefügt."""

    minimum_frischlufttemperatur_bypass_aus = gauge(19, 0.01, signed=True, unit='°C', writable=True)  # Minimum Frischlufttemperatur (Bypass AUS)
    bypasstemperatur_hysterese = gauge(102, 0.01, signed=True, unit='°C', writable=True)  # Bypasstemperatur Hysterese
    bypass_laufzeit_an_aus = integer(107, signed=False, unit='Sekunden', writable=True)  # Bypass laufzeit (AN/AUS)

class HauptmenuInfo(Component):
    """Gerätemodell/-typ (A03/A04). Neu hinzugefügt."""

    geraete_modell_0_fwt_1_p = integer(17, signed=False, unit='AUS/AN')  # Geräte Modell (0=FWT, 1=P)
    geraete_typ_0_nur_heizen_1_heizen_und_kuehlen = integer(18, signed=False, unit='AUS/AN')  # Geräte typ (0=Nur Heizen, 1=Heizen und Kühlen)
