"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand.

Re-run ``python tools/generate_registers.py`` from the repository root after
changing the curation rules in that script (e.g. to include more registers
from the Excel register list).
"""

from __future__ import annotations

from modbus_connection.model import Component, gauge, integer


class Lueftung(Component):
    """Betriebsart, Lüfterstufe und Intensivlüftung. Migriert 1:1 aus proxon.yaml."""

    proxon_betriebsart = integer(16, signed=False, writable=True)  # Proxon Betriebsart
    proxon_luefterstufe = integer(22, signed=False, writable=True)  # Lüfterstufe (innen)
    proxon_intensivlueftung_restzeit = integer(133, signed=False, unit='Minuten')  # Proxon Intensivlüftung Restzeit
    proxon_intensivlueftung_sollzeit = integer(189, signed=False, unit='Minuten')  # Proxon Intensivlüftung Sollzeit
    proxon_heizelemente_global = integer(325, signed=False, unit='AUS/AN', writable=True)  # Heizelemente Global freigeben

class T300Warmwasser(Component):
    """T300 Warmwasser-Heizstab. Migriert 1:1 aus proxon.yaml."""

    proxon_kuehlung = integer(62, signed=False, unit='AUS/AN', writable=True)  # Proxon Kuehlung
    proxon_soll_temperatur_wasser = gauge(2000, 0.1, signed=False, unit='°C', writable=True)  # Proxon Soll-Temperatur Wasser
    t300_heizstab = integer(2001, signed=False, unit='AUS/AN', writable=True)  # Heizstab
    proxon_heizstab_temperatur = gauge(2003, 0.1, signed=False, unit='°C', writable=True)  # Proxon Heizstab Temperatur

class Geraetefilter(Component):
    """Standzeit/Nutzzeit des Gerätefilters. Migriert 1:1 aus proxon.yaml."""

    proxon_standzeit_fwt_geraetefilter = integer(460, signed=False, unit='Monate')  # Proxon Standzeit FWT Gerätefilter
    proxon_nutzzeit_fwt_geraetefilter = integer(469, signed=False)  # Proxon Nutzzeit FWT Gerätefilter

class ModbusStatusHolding(Component):
    """Modbus-Statusregister. Migriert 1:1 aus proxon.yaml."""

    proxon_modbus_status = integer(438, signed=False)  # Proxon Modbus Status

class Stundenzaehler(Component):
    """Betriebsstundenzähler (S01-S33). Neu hinzugefügt (nicht in der bisherigen proxon.yaml)."""

    stunden_fwt_an = integer(467, signed=False)  # Stunden FWT AN
    stunden_umluftfilter = integer(468, signed=False)  # Stunden Umluftfilter
    stunden_vorwaerme_an = integer(470, signed=False)  # Stunden Vorwärme AN
    stunden_umluft_an = integer(471, signed=False)  # Stunden Umluft AN
    stunden_fu_an = integer(472, signed=False)  # Stunden FU AN
    stunden_kompressor_kuehlen = integer(473, signed=False)  # Stunden Kompressor Kühlen
    stunden_kompressor_heizen = integer(474, signed=False)  # Stunden Kompressor Heizen
    stunden_abtau_an = integer(475, signed=False)  # Stunden Abtau AN
    stunden_ventilatoren_stufe_1 = integer(476, signed=False)  # Stunden Ventilatoren Stufe 1
    stunden_ventilatoren_stufe2 = integer(477, signed=False)  # Stunden Ventilatoren Stufe2
    stunden_ventilatoren_stufe_3 = integer(478, signed=False)  # Stunden Ventilatoren Stufe 3
    stunden_ventilatoren_stufe_4 = integer(479, signed=False)  # Stunden Ventilatoren Stufe 4
    stunden_ptc_heizmodul_1_relais_1_an = integer(487, signed=False)  # Stunden PTC Heizmodul 1 Relais 1 An
    stunden_ptc_heizmodul_1_relais_2_an = integer(488, signed=False)  # Stunden PTC Heizmodul 1 Relais 2 An
    stunden_ptc_heizmodul_1_relais_3_an = integer(489, signed=False)  # Stunden PTC Heizmodul 1 Relais 3 An
    stunden_ptc_heizmodul_1_relais_4_an = integer(490, signed=False)  # Stunden PTC Heizmodul 1 Relais 4 An
    stunden_ptc_heizmodul_1_relais_5_an = integer(491, signed=False)  # Stunden PTC Heizmodul 1 Relais 5 An
    stunden_ptc_heizmodul_1_relais_6_an = integer(492, signed=False)  # Stunden PTC Heizmodul 1 Relais 6 An
    stunden_ptc_heizmodul_1_relais_7_an = integer(493, signed=False)  # Stunden PTC Heizmodul 1 Relais 7 An
    stunden_ptc_heizmodul_1_relais_8_an = integer(494, signed=False)  # Stunden PTC Heizmodul 1 Relais 8 An
    stunden_ptc_heizmodul_1_relais_9_an = integer(495, signed=False)  # Stunden PTC Heizmodul 1 Relais 9 An
    stunden_ptc_heizmodul_1_relais_10_an = integer(496, signed=False)  # Stunden PTC Heizmodul 1 Relais 10 An
    stunden_ptc_heizmodul_2_relais_1_an = integer(497, signed=False)  # Stunden PTC Heizmodul 2 Relais 1 An
    stunden_ptc_heizmodul_2_relais_2_an = integer(498, signed=False)  # Stunden PTC Heizmodul 2 Relais 2 An
    stunden_ptc_heizmodul_2_relais_3_an = integer(499, signed=False)  # Stunden PTC Heizmodul 2 Relais 3 An
    stunden_ptc_heizmodul_2_relais_4_an = integer(500, signed=False)  # Stunden PTC Heizmodul 2 Relais 4 An
    stunden_ptc_heizmodul_2_relais_5_an = integer(501, signed=False)  # Stunden PTC Heizmodul 2 Relais 5 An
    stunden_ptc_heizmodul_2_relais_6_an = integer(502, signed=False)  # Stunden PTC Heizmodul 2 Relais 6 An
    stunden_ptc_heizmodul_2_relais_7_an = integer(503, signed=False)  # Stunden PTC Heizmodul 2 Relais 7 An
    stunden_ptc_heizmodul_2_relais_8_an = integer(504, signed=False)  # Stunden PTC Heizmodul 2 Relais 8 An
    stunden_ptc_heizmodul_2_relais_9_an = integer(505, signed=False)  # Stunden PTC Heizmodul 2 Relais 9 An
    stunden_ptc_heizmodul_2_relais_10_an = integer(506, signed=False)  # Stunden PTC Heizmodul 2 Relais 10 An

class Bypass(Component):
    """Bypass-Einstellungen (G01-G03). Neu hinzugefügt."""

    minimum_frischlufttemperatur_bypass_aus = gauge(19, 0.01, signed=True, unit='°C', writable=True)  # Minimum Frischlufttemperatur (Bypass AUS)
    bypasstemperatur_hysterese = gauge(102, 0.01, signed=True, unit='°C', writable=True)  # Bypasstemperatur Hysterese
    bypass_laufzeit_an_aus = integer(107, signed=False, unit='Sekunden', writable=True)  # Bypass laufzeit (AN/AUS)

class HauptmenuInfo(Component):
    """Gerätemodell/-typ (A03/A04). Neu hinzugefügt."""

    geraete_modell_0_fwt_1_p = integer(17, signed=False, unit='AUS/AN')  # Geräte Modell (0=FWT, 1=P)
    geraete_typ_0_nur_heizen_1_heizen_und_kuehlen = integer(18, signed=False, unit='AUS/AN')  # Geräte typ (0=Nur Heizen, 1=Heizen und Kühlen)
