"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand.

Re-run ``python tools/generate_registers.py`` from the repository root after
changing the curation rules in that script (e.g. to include more registers
from the Excel register list).
"""

from __future__ import annotations

from modbus_connection.model import Component, gauge, integer


class ZonenTemperaturen(Component):
    """Ist-Temperaturen je Raum/Zone. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_ist_temperatur_partykeller = gauge(40, 0.01, signed=False, unit='°C')  # Partykeller
    proxon_ist_temperatur_wohnzimmer = gauge(41, 0.01, signed=False, unit='°C')  # Wohnzimmer
    proxon_heizelement_status = integer(574, signed=True, unit='Binär')  # Bit9:R10 Bit8:R9 Bit7:R8 Bit6:R7 Bit5:R6 Bit4:R5 Bit3:R4 Bit2:R3 Bit1:R2 Bit0:R1
    proxon_heizelement_status_2 = integer(583, signed=True, unit='Binär')  # Bit9:R10 Bit8:R9 Bit7:R8 Bit6:R7 Bit5:R6 Bit4:R5 Bit3:R4 Bit2:R3 Bit1:R2 Bit0:R1
    proxon_ist_temperatur_590 = gauge(590, 0.1, signed=True, unit='°C')  # NONE
    proxon_ist_temperatur_flur = gauge(593, 0.1, signed=True, unit='°C')  # Flur
    proxon_ist_temperatur_schlafzimmer = gauge(596, 0.1, signed=True, unit='°C')  # Schlafzimmer
    proxon_ist_temperatur_buero = gauge(599, 0.1, signed=True, unit='°C')  # Büro
    proxon_ist_temperatur_lea = gauge(602, 0.1, signed=True, unit='°C')  # Lea
    proxon_ist_temperatur_vorraum = gauge(605, 0.1, signed=True, unit='°C')  # Vorraum
    proxon_ist_temperatur_werkstatt = gauge(608, 0.1, signed=True, unit='°C')  # Werkstatt

class ZuAbluft(Component):
    """Zu-/Ab-/Fort-/Frischluft-Temperaturen, CO2, Luftfeuchte. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_co2_wohnzimmer = integer(21, signed=True, unit='ppm')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_luftfeuchte_wohnzimmer = integer(22, signed=True, unit='%')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_temperatur_zuluft = gauge(195, 0.01, signed=False, unit='°C')  # Proxon Temperatur Zuluft
    proxon_temperatur_abluft = gauge(196, 0.01, signed=False, unit='°C')  # Proxon Temperatur Abluft
    proxon_temperatur_fortluft = gauge(197, 0.01, signed=False, unit='°C')  # Proxon Temperatur Fortluft
    proxon_temperatur_frischluft = gauge(198, 0.01, signed=False, unit='°C')  # Proxon Temperatur Frischluft

class WarmwasserInput(Component):
    """T300 Warmwasser Ist-Temperaturen. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_temperatur_wasser_unten = gauge(813, 0.1, signed=False, unit='°C')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_ist_temperatur_wasser = gauge(814, 0.1, signed=False, unit='°C')  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).

class HeizstabStatus(Component):
    """T300 Heizstab-/Kompressorstatus (binäre Sensoren). Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_kompressor_status = integer(824, signed=False)  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).
    proxon_heizstab_status = integer(826, signed=False)  # Nicht in der FWT2.0-Registerliste (separates Modul, z.B. T300).

class SonstigesInput(Component):
    """Betriebsart, Lüfterstufe, Stromaufnahme u.a. Migriert 1:1 aus proxon.yaml."""

    register_space = "input"

    proxon_stromaufnahme_total = gauge(25, 0.1, signed=True)  # Stromaufnahme
    proxon_lueftungsstufe_ventilator_zuluft = integer(154, signed=True)  # Proxon Lüftungsstufe Ventilator Zuluft
    proxon_aktueller_betrieb = integer(241, signed=True)  # Proxon aktueller Betrieb

class Betriebswerte(Component):
    """Ventilatoren, Leistung, JAZ-Zähler, Betriebsart/Status/Fehlercodes, Messtemperaturen T1-T14, Ventilpositionen, Drücke. Neu hinzugefügt."""

    register_space = "input"

    akt_drehzahl_zuluftventilator = integer(0, signed=True, unit='rpm')  # Akt.Drehzahl ZuLuftventilator
    akt_drehzahl_abluftventilator = integer(1, signed=True, unit='rpm')  # Akt.Drehzahl AbLuftventilator
    ptc_kuehlen_freigabe = integer(3, signed=True)  # PTC Kühlen Freigabe
    nacht_temp_bei_zeitprogramm = gauge(4, 0.01, signed=False, unit='°C')  # Nacht Temp Bei Zeitprogramm
    firmwareversionhaupptplatine = gauge(5, 0.1, signed=True)  # FirmwareVersionHaupptPlatine
    relaisstatushauptplatine = integer(8, signed=True, unit='Binär')  # RelaisStatusHauptPlatine
    es997stufe = integer(10, signed=True)  # ES997Stufe
    sollzone2 = gauge(11, 0.01, signed=False)  # SollZone2
    adsusaettemp = integer(12, signed=True)  # ADSusaetTemp
    adausentemp = integer(13, signed=True)  # ADAusenTemp
    clockhour = integer(14, signed=True)  # ClockHour
    clockmin = integer(15, signed=True)  # ClockMin
    clockday = integer(16, signed=True)  # ClockDay
    clockdate = integer(17, signed=True)  # ClockDate
    clockmonth = integer(18, signed=True)  # ClockMonth
    powerpcb = gauge(19, 0.1, signed=True)  # PowerPCB
    powerfu = gauge(20, 0.1, signed=True)  # PowerFU
    akt_betriebsart = integer(23, signed=True)  # Akt. Betriebsart
    p18_druckventilator = gauge(24, 0.1, signed=True, unit='Pa')  # P18 Druckventilator
    air_m3_h = gauge(26, 0.1, signed=True)  # Air m3/h
    jaz_komp_1min = gauge(27, 0.01, signed=True)  # JAZ KOMP 1min
    jaz_komp_1_stunde = gauge(28, 0.01, signed=True)  # JAZ KOMP  1 stunde
    jaz_komp_24_stunde = gauge(29, 0.01, signed=True)  # JAZ KOMP  24 stunde
    jaz_komp_365_tage = gauge(30, 0.01, signed=True)  # JAZ KOMP  365 tage
    jaz_komp_days = integer(31, signed=True)  # JAZ KOMP  days
    jaz_total_1min = gauge(32, 0.01, signed=True)  # JAZ Total 1min
    jaz_total_1_stunde = gauge(33, 0.01, signed=True)  # JAZ Total  1 stunde
    jaz_total_24_stunde = gauge(34, 0.01, signed=True)  # JAZ Total  24 stunde
    jaz_total_365_tage = gauge(35, 0.01, signed=True)  # JAZ Total  365 tage
    jaz_total_days = integer(36, signed=True)  # JAZ Total  days
    hp_nmt_state = integer(37, signed=True)  # HP_NMT_State
    stufebeizeitprg = integer(38, signed=True)  # StufeBeiZeitPrg
    umluftaktive = integer(39, signed=True)  # UmluftAktive
    temphbdeintern = gauge(42, 0.01, signed=False)  # TempHBDEintern
    stoerung = integer(47, signed=True)  # Stoerung
    errorstatus1 = integer(48, signed=True)  # ErrorStatus1
    errorstatus2 = integer(49, signed=True)  # ErrorStatus2
    errorstatus3 = integer(50, signed=True)  # ErrorStatus3
    errorstatus4 = integer(51, signed=True)  # ErrorStatus4
    firmwareversionnebenplatine = gauge(150, 0.1, signed=True)  # FirmwareVersionNebenPlatine
    wprelaisstatus = integer(151, signed=True, unit='Binär')  # WpRelaisStatus
    statusventilatoren = integer(152, signed=True)  # StatusVentilatoren
    ventilatorfehlerrestzeit = integer(153, signed=True, unit='Sekunden')  # VentilatorFehlerRestZeit
    akt_ventilator_spannung_zuluft = gauge(155, 0.01, signed=True, unit='Volt')  # Akt.Ventilator Spannung ZuLuft
    akt_ventilator_spannung_abluft = gauge(156, 0.01, signed=True, unit='Volt')  # Akt.Ventilator Spannung AbLuft
    errorflagsnebenplatine = integer(157, signed=True, unit='Binär')  # ErrorFlagsNebenPlatine
    bypassresthaltezeit = integer(158, signed=True, unit='Sekunden')  # BypassRestHaltezeit
    schieber_position = integer(159, signed=True)  # Schieber Position
    schieberresthaltezeit = gauge(160, 0.1, signed=True, unit='Sekunden')  # SchieberRestHaltezeit
    schieberverfahrauftrag = gauge(161, 0.1, signed=True, unit='Sekunden')  # SchieberVerfahrauftrag
    status_kompressor = integer(162, signed=True)  # Status Kompressor
    wptimerschonzeit = integer(163, signed=True, unit='Sekunden')  # WpTimerSchonzeit
    wptimermindestlaufzeit = integer(164, signed=True, unit='Sekunden')  # WpTimerMindestlaufzeit
    wpabtautimer = integer(165, signed=True, unit='Minuten')  # WpAbtauTimer
    wptimerabtaunachlauf = integer(166, signed=True, unit='Sekunden')  # WpTimerAbtauNachlauf
    p19_druckdiff_abtau = gauge(167, 0.01, signed=True, unit='Pa')  # P19 Druckdiff. Abtau
    wptimerentlastung = integer(168, signed=True, unit='Sekunden')  # WpTimerEntlastung
    wpminabtauintervalltimer = gauge(169, 0.01, signed=True, unit='Minuten')  # WpMinAbtauIntervallTimer
    fu_errorcode = integer(170, signed=True)  # FU_ErrorCode
    akt_leistung_kompressor = gauge(171, 0.01, signed=True, unit='%')  # Akt.Leistung: Kompressor
    fu_errorcode2 = integer(172, signed=True)  # FU_ErrorCode2
    delta_sauggas_kondensator_temp = gauge(173, 0.01, signed=False, unit='°C')  # Delta Sauggas Kondensator Temp
    fu_fatalfoferror = integer(174, signed=True)  # FU_FatalFOFerror
    t5_vorverdampfer = gauge(175, 0.01, signed=False, unit='°C')  # T5 VorVerdampfer
    t6_verdampfer = gauge(176, 0.01, signed=False, unit='°C')  # T6 Verdampfer
    t8_nach_vorwaerme = gauge(177, 0.01, signed=False, unit='°C')  # T8 Nach Vorwärme
    t12_vor_kondensator = gauge(178, 0.01, signed=False, unit='°C')  # T12 Vor Kondensator
    t10_kondensator = gauge(179, 0.01, signed=False, unit='°C')  # T10 Kondensator
    t13_kompressor = gauge(180, 0.01, signed=False, unit='°C')  # T13 Kompressor
    t9_t_aul_vor_ewt = gauge(181, 0.01, signed=False, unit='°C')  # T9 T_AUL_vor_EWT
    wpabtauschwellecounter = integer(182, signed=True, unit='Sekunden')  # WpAbtauSchwelleCounter
    lscontrolfu_status = integer(183, signed=True)  # LsControlFU_Status
    lscontrolfuerrorinput = integer(184, signed=True, unit='AUS/AN')  # LsControlFUErrorInput
    furesettimecounter = integer(185, signed=True, unit='Sekunden')  # FuResetTimeCounter
    fufehlerverz = integer(186, signed=True, unit='Sekunden')  # FuFehlerVerz
    fuerrorcounter = integer(187, signed=True)  # FuErrorCounter
    lscontrolhightime = gauge(188, 0.01, signed=True, unit='Sekunden')  # LsControlHighTime
    lscontrolpulsbreite = gauge(189, 0.01, signed=True, unit='Sekunden')  # LsControlPulsbreite
    akt_drehzahl_kompressor = integer(190, signed=True, unit='ppm')  # Akt.Drehzahl: Kompressor
    tempzusatz1 = gauge(191, 0.01, signed=False, unit='°C')  # TempZusatz1
    zuluftsollzone1 = gauge(192, 0.01, signed=False, unit='°C')  # ZuluftSollZone1
    tempzusatz2 = gauge(193, 0.01, signed=False, unit='°C')  # TempZusatz2
    zuluftsollzone2 = gauge(194, 0.01, signed=False, unit='°C')  # ZuluftSollZone2
    tcanforderungluft = gauge(199, 0.01, signed=True, unit='%')  # TcAnforderungLuft
    conwpstoptimer = integer(200, signed=True, unit='Sekunden')  # ConWpStopTimer
    akt_max_leistung_kompressor = gauge(201, 0.01, signed=True, unit='%')  # Akt. Max.Leistung Kompressor
    delta_sauggas_verdampfer_temp = gauge(202, 0.01, signed=False, unit='°C')  # Delta Sauggas Verdampfer Temp
    e_ventil_kuehlung_position = integer(203, signed=True)  # E-Ventil Kühlung Position
    e_ventil_heizung_position = integer(204, signed=True)  # E-Ventil Heizung Position
    e_ventil_vorwaerme_position = integer(205, signed=True)  # E-Ventil Vorwärme Position
    p14_nd_verdampfer = gauge(206, 0.001, signed=True, unit='bar')  # P14 ND. Verdampfer
    t14_sauggas_nach_kondensator = gauge(207, 0.01, signed=False, unit='°C')  # T14 Sauggas nach Kondensator
    t11_sauggas_nach_verdampfer = gauge(208, 0.01, signed=False, unit='°C')  # T11 Sauggas nach Verdampfer
    abtaudruck = gauge(209, 0.01, signed=True, unit='Pa')  # AbtauDruck
    einausstatus = integer(210, signed=True, unit='Binär')  # EinAusStatus
    akt_ventilator_stufe_abluft = integer(211, signed=True)  # Akt.Ventilator Stufe Abluft
    schieberberechnungrestzeit = integer(212, signed=True, unit='Sekunden')  # SchieberBerechnungRestZeit
    wptimerauslauf = integer(214, signed=True, unit='Sekunden')  # WpTimerAuslauf
    restwpzusatzabtauverzzeit = integer(215, signed=True, unit='Sekunden')  # RestWpZusatzAbtauVerzZeit
    verdampfertemperatur_druck = gauge(216, 0.01, signed=False, unit='°C')  # Verdampfertemperatur (Druck)
    fuinittimecounter = gauge(217, 0.01, signed=True, unit='Sekunden')  # FuInitTimeCounter
    wpmaxr407_druckzutemp = gauge(218, 0.01, signed=False, unit='°C')  # WpMaxR407_DruckZuTemp
    stufectrlby = integer(219, signed=True)  # StufeCtrlBy
    erdwaerme_zustand = integer(220, signed=True, unit='AUS/AN')  # Erdwärme Zustand
    zustand_magnetventil_aus_an = integer(221, signed=True, unit='AUS/AN')  # Zustand Magnetventil AUS/AN
    zustand_bypass = integer(222, signed=True, unit='AUS/AN')  # Zustand Bypass
    zustand_4_wegeventil_heizen_kuehlen = integer(223, signed=True, unit='AUS/AN')  # Zustand 4-Wegeventil Heizen/Kühlen
    vorwaermeventilzustand = integer(224, signed=True, unit='AUS/AN')  # VorwärmeVentilZustand
    fuleistungmodbus = integer(225, signed=True, unit='%')  # FuLeistungModbus
    fu_temperaturepowermodule = integer(233, signed=False, unit='°C')  # FU_TemperaturePowermodule
    fu_temperaturecabinet = integer(234, signed=False, unit='°C')  # FU_TemperatureCabinet
    regluftstufezuluft = integer(238, signed=True)  # RegLuftStufeZuluft
    regluftstufeabluft = integer(239, signed=True)  # RegLuftStufeAbluft
    stepstatepreh = integer(240, signed=True)  # StepStatePreH
    stepsetpointpospreh = integer(242, signed=True)  # StepSetpointPosPreH
    stepstatecool = integer(243, signed=True)  # StepStateCool
    soll_ueberhitzung = gauge(244, 0.01, signed=False, unit='°C')  # Soll Überhitzung
    stepsetpointposcool = integer(245, signed=True)  # StepSetpointPosCool
    stepsetpointposheat = integer(247, signed=True)  # StepSetpointPosHeat
    stepstateheat = integer(248, signed=True)  # StepStateHeat
    delta_soll_t8_akt_t8 = gauge(249, 0.01, signed=False, unit='°C')  # Delta Soll T8 - Akt.T8
    fu_motorcurrent = gauge(250, 0.01, signed=False, unit='Ampere')  # FU_MotorCurrent
    sollzonentemperatur2 = gauge(251, 0.01, signed=False, unit='°C')  # SollZonenTemperatur2
    akt_min_ueberhitzung = gauge(252, 0.01, signed=False, unit='°C')  # Akt. Min. Überhitzung
    akt_max_ueberhitzung = gauge(253, 0.01, signed=False, unit='°C')  # Akt. Max. Überhitzung
    fu_motor_strom = gauge(254, 0.01, signed=True, unit='Ampere')  # FU Motor Strom
    regel_freigabe_restzeit_nach_abtau = integer(255, signed=True, unit='Sekunden')  # Regel Freigabe Restzeit Nach Abtau
    nachabtauleistungrestorevalue = gauge(256, 0.01, signed=True, unit='%')  # NachAbtauLeistungRestoreValue
    nachabtausuperheatrestorevalue = gauge(257, 0.01, signed=False, unit='°C')  # NachAbtauSuperheatRestoreValue
    fumaxrpmupdatatet_fl = integer(258, signed=True, unit='AUS/AN')  # FuMaxRpmUpdatatet_fl
    fumaxrpmset = integer(259, signed=True, unit='ppm')  # FuMaxRpmSet
    nachabtaumaxsuperheat = gauge(260, 0.01, signed=False, unit='°C')  # NachAbtauMaxSuperHeat
    eventilstartpostimeleft = integer(261, signed=True)  # EventilStartPosTimeLeft
    currentes997betriebsart = integer(262, signed=True)  # CurrentES997Betriebsart
    t2_1_zonentemperatur1 = gauge(263, 0.01, signed=False, unit='°C')  # T2.1 ZonenTemperatur1
    t2_2_zonentemperatur2 = gauge(264, 0.01, signed=False, unit='°C')  # T2.2 ZonenTemperatur2
    sollzonentemperatur1 = gauge(265, 0.01, signed=False, unit='°C')  # SollZonenTemperatur1

class Heizmodule(Component):
    """Status/Temperatur/Selbsttest der beiden PTC-Heizmodule. Neu hinzugefügt."""

    register_space = "input"

    heizmodul_1_selbsttest_ergebnis = integer(570, signed=True, unit='Binär')  # Heizmodul 1 Selbsttest-Ergebnis
    heizmodul_1_status = integer(571, signed=True)  # Heizmodul 1 Status
    heizmodul_1_temperatur = integer(573, signed=True, unit='°C')  # Heizmodul 1 Temperatur
    heizmodul_2_selbsttest_ergebnis = integer(579, signed=True, unit='Binär')  # Heizmodul 2 Selbsttest-Ergebnis
    heizmodul_2_status = integer(580, signed=True)  # Heizmodul 2 Status
    heizmodul_2_temperatur = integer(582, signed=True, unit='°C')  # Heizmodul 2 Temperatur

class BedienteilStatus(Component):
    """Status der Bedienteile (Nebenbedienteile) je installierter Zone. Neu hinzugefügt."""

    register_space = "input"

    hnbe_status = integer(588, signed=True)  # HNBE Status
    nbe1_status = integer(591, signed=True)  # NBE1 Status
    nbe2_status = integer(594, signed=True)  # NBE2 Status
    nbe3_status = integer(597, signed=True)  # NBE3 Status
    nbe4_status = integer(600, signed=True)  # NBE4 Status
    nbe5_status = integer(603, signed=True)  # NBE5 Status
    nbe6_status = integer(606, signed=True)  # NBE6 Status
