"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.switch import SwitchEntity, SwitchEntityDescription
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription


@dataclass(frozen=True, kw_only=True)
class ProxonSwitchEntityDescription(SwitchEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed switch."""


class ProxonSwitch(ProxonEntity, SwitchEntity):
    """A single Proxon switch entity."""

    entity_description: ProxonSwitchEntityDescription

    @property
    def is_on(self) -> bool:
        return bool(self._value)

    async def async_turn_on(self, **kwargs) -> None:
        await self._async_write(True)

    async def async_turn_off(self, **kwargs) -> None:
        await self._async_write(False)


SWITCH_DESCRIPTIONS: tuple[ProxonSwitchEntityDescription, ...] = (
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_wohnzimmer',
        component='heizelemente_switches',
        field='proxon_heizelement_wohnzimmer',
        name='Proxon Heizelement Wohnzimmer',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_partykeller',
        component='heizelemente_switches',
        field='proxon_heizelement_partykeller',
        name='Proxon Heizelement Partykeller',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_flur',
        component='heizelemente_switches',
        field='proxon_heizelement_flur',
        name='Proxon Heizelement Flur',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_schlafzimmer',
        component='heizelemente_switches',
        field='proxon_heizelement_schlafzimmer',
        name='Proxon Heizelement Schlafzimmer',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_buro',
        component='heizelemente_switches',
        field='proxon_heizelement_buero',
        name='Proxon Heizelement Büro',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_lea',
        component='heizelemente_switches',
        field='proxon_heizelement_lea',
        name='Proxon Heizelement Lea',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_vorraum',
        component='heizelemente_switches',
        field='proxon_heizelement_vorraum',
        name='Proxon Heizelement Vorraum',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelement_werkstatt',
        component='heizelemente_switches',
        field='proxon_heizelement_werkstatt',
        name='Proxon Heizelement Werkstatt',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelemente_global',
        component='heizelemente_switches',
        field='proxon_heizelemente_global',
        name='Proxon Heizelemente Global',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_partykeller',
        component='tastensperre',
        field='proxon_tastensperre_partykeller',
        name='Proxon Tastensperre Partykeller',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_flur',
        component='tastensperre',
        field='proxon_tastensperre_flur',
        name='Proxon Tastensperre Flur',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_schlafzimmer',
        component='tastensperre',
        field='proxon_tastensperre_schlafzimmer',
        name='Proxon Tastensperre Schlafzimmer',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_buro',
        component='tastensperre',
        field='proxon_tastensperre_buero',
        name='Proxon Tastensperre Büro',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_lea',
        component='tastensperre',
        field='proxon_tastensperre_lea',
        name='Proxon Tastensperre Lea',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_vorraum',
        component='tastensperre',
        field='proxon_tastensperre_vorraum',
        name='Proxon Tastensperre Vorraum',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_tastensperre_werkstatt',
        component='tastensperre',
        field='proxon_tastensperre_werkstatt',
        name='Proxon Tastensperre Werkstatt',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_kuehlung',
        component='t300_warmwasser',
        field='proxon_kuehlung',
        name='Proxon Kuehlung',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizstab',
        component='t300_warmwasser',
        field='t300_heizstab',
        name='T300 Heizstab',
        has_entity_name=False,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon switch entities."""
    coordinator = entry.runtime_data.coordinator
    async_add_entities(ProxonSwitch(coordinator, d) for d in SWITCH_DESCRIPTIONS)

