"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.switch import SwitchEntity, SwitchEntityDescription
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription
from .zones import ZoneInfo


@dataclass(frozen=True, kw_only=True)
class ProxonSwitchEntityDescription(SwitchEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed switch."""


class ProxonSwitch(ProxonEntity, SwitchEntity):
    """A single Proxon switch entity."""

    entity_description: ProxonSwitchEntityDescription

    @property
    def is_on(self) -> bool:
        return bool(self._value)

    async def async_turn_on(self, **kwargs) -> None:
        await self._async_write(True)

    async def async_turn_off(self, **kwargs) -> None:
        await self._async_write(False)


SWITCH_DESCRIPTIONS: tuple[ProxonSwitchEntityDescription, ...] = (
    ProxonSwitchEntityDescription(
        key='proxon_kuehlung',
        component='lueftung',
        field='proxon_kuehlung',
        name='Proxon Kuehlung',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizelemente_global',
        component='lueftung',
        field='proxon_heizelemente_global',
        name='Proxon Heizelemente Global',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizstab',
        component='t300_warmwasser',
        field='t300_heizstab',
        name='T300 Heizstab',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_legionellaschutz',
        component='t300_warmwasser',
        field='legionellaschutz',
        translation_key='proxon_legionellaschutz',
        has_entity_name=True,
    ),
)

def _zone_descriptions(zones: list[ZoneInfo]) -> list[ProxonSwitchEntityDescription]:
    """One Heizelement switch per zone."""
    out: list[ProxonSwitchEntityDescription] = []
    for zone in zones:
        component = "zbp" if zone.kind == "zbp" else "nb_zones_holding"
        out.append(
            ProxonSwitchEntityDescription(
                key=f"proxon_heizelement_{zone.slug}",
                component=component,
                field="heizelement",
                zone_index=zone.zone_index,
                translation_key="proxon_zone_heizelement",
                has_entity_name=True,
            )
        )
    return out


from .intensivlueftung import INTENSIVLUEFTUNG_DESCRIPTION, ProxonIntensivlueftungSwitch


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon switch entities."""
    coordinator = entry.runtime_data.coordinator
    entities = [ProxonSwitch(coordinator, d) for d in SWITCH_DESCRIPTIONS]
    entities += [ProxonSwitch(coordinator, d) for d in _zone_descriptions(entry.runtime_data.zones)]
    entities.extend([ProxonIntensivlueftungSwitch(coordinator, INTENSIVLUEFTUNG_DESCRIPTION)])
    async_add_entities(entities)

