"""AUTO-GENERATED by tools/generate_registers.py - do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.switch import SwitchEntity, SwitchEntityDescription
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import ProxonConfigEntry
from .entity import ProxonEntity, ProxonEntityDescription
from .zones import ZoneInfo


@dataclass(frozen=True, kw_only=True)
class ProxonSwitchEntityDescription(SwitchEntityDescription, ProxonEntityDescription):
    """Entity description for a Proxon register-backed switch."""


class ProxonSwitch(ProxonEntity, SwitchEntity):
    """A single Proxon switch entity."""

    entity_description: ProxonSwitchEntityDescription

    @property
    def is_on(self) -> bool:
        return bool(self._value)

    async def async_turn_on(self, **kwargs) -> None:
        await self._async_write(True)

    async def async_turn_off(self, **kwargs) -> None:
        await self._async_write(False)


SWITCH_DESCRIPTIONS: tuple[ProxonSwitchEntityDescription, ...] = (
    ProxonSwitchEntityDescription(
        key='proxon_heizelemente_global',
        component='lueftung',
        field='proxon_heizelemente_global',
        name='Proxon Heizelemente Global',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_kuehlung',
        component='t300_warmwasser',
        field='proxon_kuehlung',
        name='Proxon Kuehlung',
        has_entity_name=False,
    ),
    ProxonSwitchEntityDescription(
        key='proxon_heizstab',
        component='t300_warmwasser',
        field='t300_heizstab',
        name='T300 Heizstab',
        has_entity_name=False,
    ),
)

def _zone_descriptions(zones: list[ZoneInfo]) -> list[ProxonSwitchEntityDescription]:
    """One Heizelement switch per zone, plus Tastensperre for HNBP/NBPn zones."""
    out: list[ProxonSwitchEntityDescription] = []
    for zone in zones:
        component = "zbp" if zone.kind == "zbp" else "nb_zones_holding"
        out.append(
            ProxonSwitchEntityDescription(
                key=f"proxon_heizelement_{zone.slug}",
                component=component,
                field="heizelement",
                zone_index=zone.zone_index,
                translation_key="proxon_zone_heizelement",
                translation_placeholders={"zone": zone.name},
            )
        )
        if zone.kind == "nb":
            out.append(
                ProxonSwitchEntityDescription(
                    key=f"proxon_tastensperre_{zone.slug}",
                    component="nb_zones_holding",
                    field="tastensperre",
                    zone_index=zone.zone_index,
                    translation_key="proxon_zone_tastensperre",
                    translation_placeholders={"zone": zone.name},
                    entity_category=EntityCategory.CONFIG,
                )
            )
    return out


async def async_setup_entry(
    hass: HomeAssistant, entry: ProxonConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up Proxon switch entities."""
    coordinator = entry.runtime_data.coordinator
    descriptions = [*SWITCH_DESCRIPTIONS, *_zone_descriptions(entry.runtime_data.zones)]
    async_add_entities(ProxonSwitch(coordinator, d) for d in descriptions)

