"""Dynamic per-zone Modbus register model.

The FWT2.0 supports 1 ZBP (Zentralbedienpanel, the main control panel every
installation has) + 1 optional HNBP (Hauptnebenbedienpanel) + up to 19 NBP
(Nebenbedienpanel) remote-zone panels. Unlike the "central" registers (see
model.py / registers_holding.py / registers_input.py, generated by
tools/generate_registers.py), these are modeled dynamically here, based on
however many zones the user configures in the config flow wizard - not
hand-written per installation.

Verified against the register list: Heizelement/PTC-freigeben (base 253),
Tastensperre (base 273), Offsettemperatur (base 213, range -3..+3°C) and
Mitteltemperatur (base 233) all follow ``base + zone_index`` for HNBP
(zone_index 0) through NBP19 (zone_index 19). The corresponding input
registers (status, Ist-Temperatur) follow ``588 + 3*zone_index`` /
``590 + 3*zone_index``. ZBP does not follow this scheme at all - it has its
own fixed addresses, no Tastensperre/Mitteltemperatur register, and its
setpoint is an *absolute* target temperature (10-30°C) rather than a ±3°C
offset from a running average.

HNBP plays a special role beyond "just another zone": the whole-house target
temperature is set on ZBP, but whether it is actually reached also depends on
HNBP's measured temperature (the device's Zone-1/Zone-2 control loop). This
does not change how HNBP is modeled here - it gets the same NbZone/NbZoneInput
shape as every NBPn - it is only worth knowing when interpreting its readings.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from homeassistant.core import HomeAssistant
from homeassistant.helpers import area_registry as ar
from modbus_connection.model import Component, gauge, integer, repeating_group

from .const import (
    CONF_HAS_HNB,
    CONF_HNB_NAME,
    CONF_ZBP_NAME,
    CONF_ZONE_COUNT,
    CONF_ZONE_NAMES,
)
from .util import slugify


@dataclass(frozen=True, kw_only=True)
class ZoneInfo:
    """One configured zone (ZBP, HNBP, or NBPn), built from the config entry."""

    name: str
    slug: str
    kind: Literal["zbp", "nb"]
    zone_index: int | None  # None for ZBP; 0=HNBP, 1..19=NBPn for "nb"
    area_id: str | None = None


def _resolve_area(hass: HomeAssistant, area_id: str) -> str:
    """Turn a Home Assistant Area id (as picked in the config flow's
    AreaSelector) into a display name + slug. Falls back to treating the
    stored value as a plain name if it isn't a known area id (e.g. the area
    was since deleted, or the entry predates the AreaSelector)."""
    area = ar.async_get(hass).async_get_area(area_id)
    name = area.name if area is not None else area_id
    return name


def zones_from_entry_data(hass: HomeAssistant, data: dict) -> list[ZoneInfo]:
    """Build the ordered zone list from a config entry's data.

    Zone names come from Home Assistant's Area registry (the config flow uses
    an AreaSelector) - `data` stores area ids, resolved here to the area's
    current display name. Order matches the wizard/reconfigure form and, for
    the original 8-room installation this integration was built for,
    reproduces the exact unique_ids the legacy proxon.yaml used (ZBP=
    Wohnzimmer, HNBP=Partykeller, NBP1-6=Flur/Schlafzimmer/Buro/Lea/Vorraum/
    Werkstatt) as long as the same Areas are picked in the same order - see
    README.
    """
    zbp_area = data[CONF_ZBP_NAME]
    zbp_name = _resolve_area(hass, zbp_area)
    zones = [ZoneInfo(name=zbp_name, slug=slugify(zbp_name), kind="zbp", zone_index=None, area_id=zbp_area)]
    if data.get(CONF_HAS_HNB):
        hnb_area = data[CONF_HNB_NAME]
        hnb_name = _resolve_area(hass, hnb_area)
        zones.append(
            ZoneInfo(name=hnb_name, slug=slugify(hnb_name), kind="nb", zone_index=0, area_id=hnb_area)
        )
    for i, area_id in enumerate(data.get(CONF_ZONE_NAMES, [])[: data.get(CONF_ZONE_COUNT, 0)], start=1):
        name = _resolve_area(hass, area_id)
        zones.append(ZoneInfo(name=name, slug=slugify(name), kind="nb", zone_index=i, area_id=area_id))
    return zones

# Offset-Temperatur is only adjustable ±3°C from the zone's own Mitteltemperatur.
OFFSET_MIN = -3.0
OFFSET_MAX = 3.0

# ZBP's setpoint is an absolute target temperature (Excel: IST-Min/Max 10/30°C).
ZBP_SOLL_MIN = 10.0
ZBP_SOLL_MAX = 30.0


class ZbpZone(Component):
    """ZBP (Zentralbedienpanel) - present exactly once on every installation."""

    heizelement = integer(187, signed=False, writable=True)
    soll_temperatur = gauge(70, 0.01, signed=True, writable=True)


class ZbpZoneInput(Component):
    """Input registers for ZBP: Ist-Temperatur, plus CO2/Luftfeuchte (only ever
    wired up at ZBP so far - kept here rather than in the generated central
    registers, but not fully verified against the official register list)."""

    register_space = "input"

    ist_temperatur = gauge(41, 0.01, signed=False)
    co2 = integer(21, signed=True)
    luftfeuchte = integer(22, signed=True)


class NbZone(Component):
    """One HNBP/NBPn zone. Instantiated (zone_count + 1) times via
    repeating_group() - index 0 is HNBP, 1..19 are NBP1..NBP19."""

    heizelement = integer(253, signed=False, writable=True)
    tastensperre = integer(273, signed=False, writable=True)
    offset_temperatur = integer(213, signed=True, writable=True)
    mitteltemperatur = integer(233, signed=True)


class NbZoneInput(Component):
    register_space = "input"

    status = integer(588, signed=True)
    ist_temperatur = gauge(590, 0.1, signed=True)


def build_nb_zones_group(count: int) -> type[Component]:
    """A Component class whose `.zones` is `count` NbZone instances.

    `count` must include the HNBP slot: pass zone_count + 1 (zone_count being
    the number of NBP1..NBPn zones from the config entry).
    """
    return type(f"NbZonesGroup{count}", (Component,), {"zones": repeating_group(count, NbZone, stride=1)})


def build_nb_zones_input_group(count: int) -> type[Component]:
    return type(
        f"NbZonesInputGroup{count}",
        (Component,),
        {"register_space": "input", "zones": repeating_group(count, NbZoneInput, stride=3)},
    )
